ZSH=$HOME/.zsh

if [[ $(uname) == "Darwin" ]]; then
	SYSTEM="mac"
else
	SYSTEM="linux"
fi

# System-specific
if [[ $SYSTEM == "mac" ]]; then
	export PATH=/Users/pekko/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:$PATH
	alias geoiplookup='geoiplookup -f /opt/local/share/GeoIP/GeoLiteCity.dat'

    pman () { man -t $* | open -a Preview -f }
    alias locate='echo "On mac, use mdfind"'
    alias ls='gls --color=auto'
else
	alias ls='ls --color=auto'
fi

source $ZSH/aliases.zsh
source $ZSH/git.zsh
source $ZSH/keys.zsh
source $ZSH/theme-and-appearance.zsh
source $ZSH/pecko.zsh-theme
source $ZSH/history.zsh

LESS="$LESS -f"

if [[ -e $HOME/.zshrc-custom ]]; then
		source $HOME/.zshrc-custom;
fi
